allowBuilds:
  "@parcel/watcher": false

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.2
  vite-plus: 0.2.2
  vitest: 4.1.9
  "@vitest/browser-playwright": 4.1.9

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
